local fzf = require("fzf-lua")
fzf.setup()

vim.keymap.set("n", "<leader>ff", fzf.files, { desc = "Find files" })
vim.keymap.set("n", "<leader>fw", fzf.live_grep, { desc = "Find word" })
vim.keymap.set("n", "<leader>fb", fzf.buffers, { desc = "Find buffer" })
vim.keymap.set("n", "<leader>o", fzf.oldfiles, { desc = "Find recently opened" })
vim.keymap.set("n", "<leader>gr", fzf.lsp_references, { desc = "Find references" })
vim.keymap.set("n", "<leader>ds", fzf.lsp_document_symbols, { desc = "Find document symbols" })
vim.keymap.set("n", "<leader>dd", fzf.lsp_document_diagnostics, { desc = "Find document diagnostics" })
